@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":AddCommand": execute()
activate ":AddCommand"

":AddCommand" -> ":Parser": parseItemForAdding(currentUserInput)
activate ":Parser"
":AddCommand" <-- ":Parser": Item
deactivate ":Parser"

alt itemName contains ' | '

    <-- ":AddCommand": Tell user not to use ' | '

else

    ":AddCommand" -> ":ItemList": addItem(Item)
    activate ":ItemList"

    ":AddCommand" <-- ":ItemList": qtyOfItem
    deactivate ":ItemList"

    alt qtyOfItem > 1

        ":AddCommand" -> ":Ui": printReactionToAddingExistingItem()
        activate ":Ui"
        ":AddCommand" <-- ":Ui"
        deactivate ":Ui"

    else else
        ":AddCommand" -> ":Ui": printReactionToAddingItem()
        activate ":Ui"
        ":AddCommand" <-- ":Ui"
        deactivate ":Ui"

    end

    <-- ":AddCommand"
    deactivate ":AddCommand"
end


@enduml