@startuml
'https://plantuml.com/class-diagram

autonumber

-> "ExpiringCommand:Command": execute()
activate "ExpiringCommand:Command"

"ExpiringCommand:Command" -> "ExpiringCommand:Command" : sortByExpiry :String
"ExpiringCommand:Command" -> ":ItemList": getItemList(sortByExpiry)
activate ":ItemList"
"ExpiringCommand:Command" <--":ItemList": listOfItems :ArrayList<Item>
deactivate ":ItemList"
"ExpiringCommand:Command" -> ":Ui": printExpiringMessage(listOfItems)
activate ":Ui"
"ExpiringCommand:Command" <-- ":Ui"
deactivate ":Ui"

<-- "ExpiringCommand:Command"
deactivate "ExpiringCommand:Command"

@enduml