@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":Notification": Notification()
activate ":Notification"

    opt isNotificationOn() && isMoreThan4Hours()
        ":Notification" -> ":Notification": printHealthNotification()
        ":Notification" -> ":Notification": printExpiryNotification();
        <-- ":Notification"
    end


-> ":NotificationCommand": execute()
activate ":NotificationCommand"

    alt isNotificationOn()
        ":NotificationCommand" -> ":Notification": setNotificationStatus(false)
        ":NotificationCommand" -> ":Ui": printLine()
        activate ":Ui"
        ":NotificationCommand" <-- ":Ui"
        deactivate ":Ui"

    else
            ":NotificationCommand" -> ":Notification": setNotificationStatus(true)
            ":NotificationCommand" -> ":Ui": printLine()
            activate ":Ui"
            ":NotificationCommand" <-- ":Ui"
            deactivate ":Ui"

    end
    <-- ":NotificationCommand"
deactivate ":NotificationCommand"

@enduml