@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":Notification": Notification()
activate ":Notification"

    ":Notification" -> ":Notification": printNotification()
    opt isNotificationOn() && isMoreThan6Hours()
        ":Notification" -> ":Notification": System.out.println(NOTIFICATION)
        ":Notification" -> ":Notification": setDateAndTime(LocalDateTime.now());
        <-- ":Notification"
    end


-> ":NotificationCommand": execute()
activate ":NotificationCommand"

    alt isNotificationOn()
        ":NotificationCommand" -> ":Notification": setNotificationStatus(false)
        ":NotificationCommand" -> ":Ui": printLine()
        activate ":Ui"
        ":NotificationCommand" <-- ":Ui"
        deactivate ":Ui"

    else
            ":NotificationCommand" -> ":Notification": setNotificationStatus(true)
            ":NotificationCommand" -> ":Ui": printLine()
            activate ":Ui"
            ":NotificationCommand" <-- ":Ui"
            deactivate ":Ui"

    end
    <-- ":NotificationCommand"
deactivate ":NotificationCommand"

@enduml