@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ResetCommand": execute()
activate ":ResetCommand"

":ResetCommand" -> ":IngredientList": getIngredientList()
activate ":IngredientList"
":ResetCommand" <-- ":IngredientList": ingredientList
deactivate ":IngredientList"

alt Ingredient List Empty
<- ":ResetCommand": FridgetException()
end

alt Reconfirm Reset Command

    ":ResetCommand" -> ":IngredientList": resetList()
    activate ":IngredientList"
    ":ResetCommand" <-- ":IngredientList":
    deactivate ":IngredientList"

    ":ResetCommand" -> ":Ui": printResetMessage()
    activate ":Ui"
    ":ResetCommand" <-- ":Ui"
    deactivate ":Ui"

    <-- ":ResetCommand"
    deactivate ":ResetCommand"
end

@enduml