@startuml
'https://plantuml.com/sequence-diagram

-> ":ShopResetCommand": execute()
activate ":ShopResetCommand"

":ShopResetCommand" -> ":ShoppingList": getShoppingList()
activate ":ShoppingList"
":ShopResetCommand" <-- ":ShoppingList": shoppingList
deactivate ":ShoppingList"

alt Shopping List Empty
<- ":ShopResetCommand": FridgetException()
end

alt Reconfirm Reset Command

    ":ShopResetCommand" -> ":ShoppingList": resetList()
    activate ":ShoppingList"
    ":ShopResetCommand" <-- ":ShoppingList":
    deactivate ":ShoppingList"

    ":ShopResetCommand" -> ":Ui": printShopResetMessage()
    activate ":Ui"
    ":ShopResetCommand" <-- ":Ui"
    deactivate ":Ui"

    <-- ":ShopResetCommand"
    deactivate ":ShopResetCommand"
end
@enduml