@startuml
hide circle
skinparam classAttributeIconSize 0

Fridget -> "1" Parser

class Fridget {
+Fridget(itemFilePath: String,
logFilePath: String shopFilePath: String)
+run(): void
+{static}main(): void
}

note top of Parser
* Constants and private variables
  are not shown in the diagram.
end note

class Parser {
+Parser()
+parseCommand(userInput: String): Command
commandType: CommandType): String
+parseItemForAdding(userInput: String): Item
+parseMultipleItemsForAdding(userInput: String): ArrayList<Item>
+parseSortTypeForList(userInput: String): String
+parseSearchTerm(userInput: String,
commandType: CommandType): String
+parseQuantity(newQty: int): boolean
+parseSuggestion(acceptSuggestion: boolean): void
}

@enduml