@startuml
'https://plantuml.com/sequence-diagram

autonumber

activate ":RemoveCommand"
activate ":RemoveCommand"

":RemoveCommand" -> ":RemoveCommand": handleRemovalOfItem(nameOfItemToBeRemoved, matchingItems)
activate ":RemoveCommand"

":RemoveCommand" -> ":RemoveCommand": handleRemovalOfMultipleQuantity(itemToBeRemoved)
activate ":RemoveCommand"

":RemoveCommand" -> ":Ui": getQuantityToBeRemoved(itemToBeRemoved)
activate ":Ui"
":RemoveCommand" <-- ":Ui": int qty
deactivate ":Ui"

":RemoveCommand" -> ":ItemList": removeItem(itemToBeRemoved, qty)
activate ":ItemList"
":RemoveCommand" <-- ":ItemList": boolean isRemoved
deactivate ":ItemList"

":RemoveCommand" -> ":Ui": printReactionToRemovingItem(itemToBeRemoved, qty)
activate ":Ui"
":RemoveCommand" <-- ":Ui"
deactivate ":Ui"

":RemoveCommand" -> ":ShoppingList": searchItemNameExist(itemToBeRemoved)
activate ":ShoppingList"
":RemoveCommand" <-- ":ShoppingList": int qtyInShop
deactivate ":ShoppingList"

opt isRemoved is true

    ":RemoveCommand" -> ":RemoveCommand": updateShopList(itemToBeRemoved, qtyInShop)
    activate ":RemoveCommand"
    ":RemoveCommand" --> ":RemoveCommand"
    deactivate ":RemoveCommand"

end

":RemoveCommand" --> ":RemoveCommand"
deactivate ":RemoveCommand"

":RemoveCommand" --> ":RemoveCommand"
deactivate ":RemoveCommand"

@enduml