@startuml
Participant ":HelpCommand" as HelpCommand

autonumber

-> HelpCommand: execute()
activate HelpCommand

    HelpCommand -> ":Ui": printLine()
    activate ":Ui"
    HelpCommand <-- ":Ui"
    deactivate ":Ui"

    <-- HelpCommand
deactivate  HelpCommand
    <-[hidden]- HelpCommand

destroy HelpCommand
@enduml