@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":HelpCommand": execute()
activate ":HelpCommand"

    ":HelpCommand" -> ":Ui": printLine()
    activate ":Ui"
    ":HelpCommand" <-- ":Ui"
    deactivate ":Ui"

    <-- ":HelpCommand"
deactivate ":HelpCommand"

@enduml