@startuml
'https://plantuml.com/class-diagram

skinparam backgroundColor #f2f2f2
skinparam defaultFontSize 16

autonumber

-> "ListCommand:Command": execute()
activate "ListCommand:Command"

"ListCommand:Command" -> ":Parser": parseSortTypeForList(currentUserInput)
activate ":Parser"
"ListCommand:Command" <-- ":Parser": sortType :String
deactivate ":Parser"
"ListCommand:Command" -> ":ItemList": getItemList(sortType)
activate ":ItemList"
"ListCommand:Command" <--":ItemList": listOfItems :ArrayList<Item>
deactivate ":ItemList"
"ListCommand:Command" -> ":Ui": printListMessage(listOfItems, sortType)
activate ":Ui"
"ListCommand:Command" <-- ":Ui"
deactivate ":Ui"

<-- "ListCommand:Command"
deactivate "ListCommand:Command"

@enduml