@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":RemoveCommand": execute()

activate ":RemoveCommand"

":RemoveCommand" -> ":Parser" : parseSearchTerm(currentUserInput, Command.Type REMOVE)
activate ":Parser"
":RemoveCommand" <-- ":Parser": String nameOfItemToBeRemoved
deactivate ":Parser"

opt nameOfItemToBeRemoved contains ' | ' or ' / '

    <-- ":RemoveCommand" : Tell user name is invalid

end

":RemoveCommand" -> ":ItemList" : findAllMatchingItems (nameOfItemToBeRemoved)
activate ":ItemList"
":RemoveCommand" <-- ":ItemList" : ArrayList<Item> matchingItems
deactivate ":ItemList"

":RemoveCommand" -> ":RemoveCommand": handleRemovalOfItem(nameOfItemToBeRemoved, matchingItems)
activate ":RemoveCommand"
":RemoveCommand" --> ":RemoveCommand"
deactivate ":RemoveCommand"

<-- ":RemoveCommand"
deactivate ":RemoveCommand"

@enduml