@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":RemoveCommand"++: execute()

":RemoveCommand" -> ":Parser"++: parseSearchTerm()

":Parser" -> ":Ui"++: getCurrentUserInput()
":Parser" <-- ":Ui"--: currentUserInput

":RemoveCommand" <-- ":Parser"--: searchTerm

alt nameOfItemToBeRemoved contains "|" or "/"

<- ":RemoveCommand": FridgetException()

else else

":RemoveCommand" -> ":ItemList"++: findAllMatchingItems(nameOfItemToBeRemoved)
":RemoveCommand" <-- ":ItemList"--: matchingItems

    group handleRemovalOfItem

        ":RemoveCommand" -> ":Ui"++: printIfNotFoundMessage(matchingItems)
        ":RemoveCommand" <-- ":Ui"--

        alt Number of Matching Item is 1

            alt Name of itemToBeRemoved != Name of matchingItem
                ":RemoveCommand" -> ":Ui"++: giveSuggestion(itemToBeRemoved)
                ":RemoveCommand" <-- ":Ui"--: acceptDefault
            end

            alt acceptDefault == true

                group handleRemovalOfMultipleQuantity

                    ":RemoveCommand" -> ":Ui"++: getQuantityToBeRemoved(itemToBeRemoved)
                    ":RemoveCommand" <-- ":Ui"--: quantity

                    ":RemoveCommand" -> ":ItemList"++: removeItem(itemToBeRemoved, quantity)
                    ":RemoveCommand" <-- ":ItemList"--: isRemoved

                    ":RemoveCommand" -> ":Ui"++: printReactionToRemovingItem(itemToBeRemoved, quantity)
                    ":RemoveCommand" <-- ":Ui"--

                    alt isRemoved == true && Name of itemToBeRemoved not in shopping list

                        group updateShopList

                            ":RemoveCommand" -> ":Ui"++: getShopQuantity(itemRemoved)
                            ":RemoveCommand" <-- ":Ui"--: quantity

                            alt quantity > 0
                                ":RemoveCommand" -> ":Item"++: <<create>>
                                ":RemoveCommand" <-- ":Item"--: addedItem

                                ":RemoveCommand" -> ":ShoppingList"++: addItem(addedItem, quantity)
                                ":RemoveCommand" <-- ":ShoppingList"--

                                ":RemoveCommand" -> ":Ui"++: printShopUpdateMessage(addedItem)
                                ":RemoveCommand" <-- ":Ui"--
                            end

                        end

                    end

                end

                <-- ":RemoveCommand"

            end

        else Number of Matching Items > 1

            ":RemoveCommand" -> ":Ui"++: matchItem(matchingItems)
            ":RemoveCommand" <-- ":Ui"--: itemToBeRemoved

            group handleRemovalOfMultipleQuantity
            end

        end

    end
    deactivate ":RemoveCommand"
end

@enduml