@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ResetCommand": execute()
activate ":ResetCommand"

":ResetCommand" -> ":ItemList": getItemList("r")
activate ":ItemList"
":ResetCommand" <-- ":ItemList": ArrayList<Item> listOfItems
deactivate ":ItemList"

opt Item List Empty
<- ":ResetCommand": FridgetException()
end

opt Reconfirm Reset Command

    ":ResetCommand" -> ":ItemList": resetList()
    activate ":ItemList"
    ":ResetCommand" <-- ":ItemList":
    deactivate ":ItemList"

    ":ResetCommand" -> ":Ui": printResetMessage()
    activate ":Ui"
    ":ResetCommand" <-- ":Ui"
    deactivate ":Ui"

    <-- ":ResetCommand"
    deactivate ":ResetCommand"
end

@enduml