@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ShopListCommand": execute()
activate ":ShopListCommand"

":ShopListCommand" -> ":ShoppingList": getShoppingList("default")
activate ":ShoppingList"
":ShopListCommand" <-- ":ShoppingList": ArrayList<Item> listOfItems
deactivate ":ShoppingList"

":ShopListCommand" -> ":Ui": printListMessage(listOfItems, "", true)
activate ":Ui"
":ShopListCommand" <-- ":Ui":
deactivate ":Ui"

<-- ":ShopListCommand"
deactivate ":ShopListCommand"

@enduml