@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ShopResetCommand": execute()
activate ":ShopResetCommand"

":ShopResetCommand" -> ":ShoppingList": getShoppingList()
activate ":ShoppingList"
":ShopResetCommand" <-- ":ShoppingList": shoppingList
deactivate ":ShoppingList"

opt Shopping List Empty
<- ":ShopResetCommand": FridgetException()
end

opt Reconfirm Reset Command

    ":ShopResetCommand" -> ":ShoppingList": resetList()
    activate ":ShoppingList"
    ":ShopResetCommand" <-- ":ShoppingList":
    deactivate ":ShoppingList"

    ":ShopResetCommand" -> ":Ui": printShopResetMessage()
    activate ":Ui"
    ":ShopResetCommand" <-- ":Ui"
    deactivate ":Ui"

    <-- ":ShopResetCommand"
    deactivate ":ShopResetCommand"
end
@enduml