@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam backgroundColor #f2f2f2
skinparam defaultFontSize 16
hide circle

ItemList "1" <-left- Fridget : shoppingList
ItemList "1" <-up- Command
Item "*" <-left- ItemList : shoppingList

class ItemList {
    + addItem(item: Item): void
    + removeItem(item: Item, qty: int): void
    + searchItemNameExist(item: Item): int
    + containsItem(item: Item): boolean
    + sortItem(): ArrayList<Item>
    + getShoppingList(sortType: String): ArrayList<Item>
    + resetList(): void
}

class Item {
    - itemName: String
    - quantity: int
}

class Command {
    + execute(ui: Ui, parser: Parser, itemList: ItemList, shoppingList: ShoppingList) : void
}

class Fridget {
    + run(): void
    + {static} main(): void
}

@enduml